### ISSUE TITLE
Next 13 compatibility

### ISSUE THREAD

**Issue by ghost** [panelbearhq/panelbear-nextjs#5]
Next 13 isn't listed as a valid peerDep. I know it's just been released, but I thought I'd post this as a heads up, since it's currently failing my build: https://github.com/ismay/portfolio/pull/96#issuecomment-1291573650

**Comment by anthonynsimon** [comment]
Thanks for reporting this! Just added Next 13 as a supported peer dep.

You can download the latest version:

```
npm install @panelbear/panelbear-nextjs@latest 

# or with yarn
yarn add @panelbear/panelbear-nextjs@latest
```

**Comment by ghost** [comment]
Awesome, thanks for the quick fix 🙏!
